`timescale 1ns / 1ps

// ------------------------------------------------------------
// kcmu_top.sv
// Top-level of KCMU IP:
// - Trace stream in/out
// - Backward-compatible simple external memory interface
// - Optional AXI-like memory bridge (queued multi-outstanding)
// ------------------------------------------------------------
module kiloware_top #(
  parameter integer ADDR_W   = 8,
  parameter integer DATA_W   = 32,
  parameter integer LINES    = 4,
  parameter integer SCORE_W  = 8,
  parameter integer TIME_W   = 16,
  parameter integer K_RECENT = 1,
  parameter bit     H2O_V2_EN = 1'b1,
  parameter bit     TRUE_H2O_RECENT_EN = 1'b1,
  parameter bit     TRUE_H2O_HH_EN = 1'b1,
  parameter bit     TRUE_H2O_BACKEND_ADMISSION_EN = 1'b1,
  parameter bit     UTILITY_HEAD_ADAPTIVE_EN = 1'b0,
  parameter bit     UTILITY_QUERY_AWARE_EN = 1'b0,
  parameter bit     UTILITY_COST_AWARE_EN = 1'b0,
  parameter bit     UTILITY_BACKEND_CRITICAL_EN = 1'b0,
  parameter bit     UTILITY_SCORE_REPL_EN = 1'b0,
  parameter bit     UTILITY_MARGINAL_REPL_EN = 1'b0,
  parameter integer MEM_RD_LATENCY = 2,
  parameter integer L2_RD_LATENCY = 1,
  parameter integer L2_LINES = 32,
  parameter integer L2_WAYS = 1,
  parameter integer L2_VB_LINES = 2,
  parameter bit     L2_VB_ENABLE = 1'b1,
  parameter bit     L2_VB_CLEAN_READONLY_EN = 1'b0,
  parameter bit     L2_WRITE_ALLOCATE = 1'b1,
  parameter bit     L2_WRITE_THROUGH_EN = 1'b1,
  parameter bit     L2_BG_DIRTY_FLUSH_EN = 1'b1,
  parameter logic [2:0] L2_WRITE_ALLOC_QOS_TH = 3'd2,
  parameter logic [2:0] L2_READ_FILL_QOS_TH = 3'd1,
  parameter logic [2:0] L2_PREFETCH_FILL_QOS_TH = 3'd3,
  parameter bit     L2_SEM_FILL_RELAX_EN = 1'b1,
  parameter bit     L2_SEM_HOT_VICTIM_PROTECT_EN = 1'b1,
  parameter logic [2:0] L2_SEM_HOT_SCORE_BONUS = 3'd3,
  parameter logic [2:0] L2_SEM_COLD_SCORE_PENALTY = 3'd2,
  parameter logic [7:0] L2_SEM_HOT_MAX_AGE = 8'd112,
  parameter logic [2:0] L2_REQ_HOT_SCORE_BONUS = 3'd2,
  parameter logic [2:0] L2_AGE_STALE_SCORE_PENALTY = 3'd2,
  parameter logic [2:0] L2_LOSSY_SCORE_PENALTY = 3'd3,
  parameter bit     L2_LOSSY_COMPRESS_EN = 1'b1,
  parameter integer L2_COMP_SHIFT = 4,
  parameter logic [2:0] L2_COMPRESS_QOS_TH = 3'd2,
  parameter logic [7:0] L2_COMP_ERR_CAP = 8'd63,
  parameter logic [2:0] L1_BYPASS_QOS_TH = 3'd1,
  parameter logic [2:0] L1_DEMAND_FILL_QOS_TH = 3'd3,
  parameter logic [2:0] L1_PREFETCH_FILL_QOS_TH = 3'd4,
  parameter logic [2:0] L1_MISS_BYPASS_QOS_TH = 3'd7,
  parameter bit     HIER_POLICY_EN = 1'b1,
  parameter logic [2:0] L1_CONGEST_BYPASS_QOS_TH = 3'd5,
  parameter logic [2:0] PREFETCH_CONGEST_QOS_TH = 3'd7,
  parameter logic [2:0] PREFETCH_HBM_ISSUE_QOS_TH = 3'd6,
  parameter bit     PREFETCH_HBM_ISSUE_RELAX_HOT = 1'b1,
  parameter integer EXEC_CONGEST_Q_LEVEL_TH = 1,
  parameter integer HBM_CONGEST_COLD_EXTRA_LAT = 3,
  parameter integer HBM_CONGEST_HOT_EXTRA_LAT = 1,
  parameter integer HBM_CONGEST_PREFETCH_EXTRA_LAT = 4,
  parameter bit     L1_FILL_ON_HBM_MISS = 1'b1,
  parameter bit     PF_ADAPT_EN = 1'b1,
  parameter logic [2:0] PF_QOS_TH = 3'd2,
  parameter integer HBM_IF_Q_DEPTH = 4,
  parameter integer HBM_IF_SERVICE_CYCLES = 1,
  parameter bit     KV_MAP_ENABLE = 1'b1,
  parameter integer KV_BLOCK_OFF_BITS = 2,
  parameter integer KV_DIR_ENTRIES = 64,
  parameter bit     KV_REAL_LAYOUT_EN = 1'b1,
  parameter integer KV_TOKEN_BLOCK_BITS = 4,
  parameter integer KV_TYPE_ADDR_BIT = -1,
  parameter bit     KV_MAP_SCORE_REPL_EN = 1'b1,
  parameter integer KV_MAP_SCORE_REPL_HW_WIN = 2,
  parameter logic [3:0] KV_MAP_SCORE_PROTECT_TH = 4'd12,
  parameter bit     KV_MAP_SCORE_DECAY_EN = 1'b1,
  parameter integer KV_MAP_SCORE_DECAY_LOG2 = 5,
  parameter bit     ATTN_SCHED_EN = 1'b1,
  parameter bit     USE_AXI_IF = 1'b0
)(
  input  logic                 clk,
  input  logic                 rst_n,

  input  logic                 prefetch_enable,

  // Trace input
  input  logic                 trace_valid,
  output logic                 trace_ready,
  input  kcmu_pkg::kcmu_op_t   trace_op,
  input  logic [ADDR_W-1:0]    trace_addr,
  input  logic [DATA_W-1:0]    trace_wdata,
  input  logic                 trace_meta_valid,
  input  logic [kcmu_pkg::KCMU_SEQ_W-1:0] trace_seq_id,
  input  kcmu_pkg::kcmu_phase_t trace_phase,
  input  kcmu_pkg::kcmu_kv_kind_t trace_kv_kind,
  input  logic [2:0]           trace_layer,
  input  logic [1:0]           trace_head,
  input  logic [11:0]          trace_token,
  input  logic [2:0]           trace_prio,

  // Descriptor trace input
  input  logic                 trace_desc_valid,
  output logic                 trace_desc_ready,
  input  kcmu_pkg::kcmu_op_t   trace_desc_op,
  input  logic [ADDR_W-1:0]    trace_desc_base_addr,
  input  logic [7:0]           trace_desc_len,
  input  logic [SCORE_W-1:0]   trace_desc_score,
  input  logic [kcmu_pkg::KCMU_SEQ_W-1:0] trace_desc_seq_id,
  input  kcmu_pkg::kcmu_phase_t trace_desc_phase,
  input  kcmu_pkg::kcmu_kv_kind_t trace_desc_kv_kind,
  input  logic                 trace_desc_attn_valid,
  input  logic [SCORE_W-1:0]   trace_desc_attn_score,
  input  logic [kcmu_pkg::KCMU_ATTN_RANK_W-1:0] trace_desc_recent_rank,
  input  logic [kcmu_pkg::KCMU_TOKEN_BLOCK_W-1:0] trace_desc_token_block_id,
  input  logic [kcmu_pkg::KCMU_ATTN_EPOCH_W-1:0] trace_desc_attn_epoch,
  input  logic [kcmu_pkg::KCMU_HEAD_BUDGET_W-1:0] trace_desc_head_budget_class,
  input  logic [SCORE_W-1:0]   trace_desc_query_relevance,
  input  logic [kcmu_pkg::KCMU_COST_CLASS_W-1:0] trace_desc_compression_risk,
  input  logic [kcmu_pkg::KCMU_COST_CLASS_W-1:0] trace_desc_spill_cost,
  input  logic [SCORE_W-1:0]   trace_desc_service_criticality,
  input  logic                 trace_desc_policy_select_s5,
  input  logic [kcmu_pkg::KCMU_DESC_CLASS_W-1:0] trace_desc_temporal_persist_class,
  input  logic [kcmu_pkg::KCMU_DESC_CLASS_W-1:0] trace_desc_reuse_distance_class,
  input  logic [kcmu_pkg::KCMU_DESC_CLASS_W-1:0] trace_desc_query_structure_class,
  input  logic [kcmu_pkg::KCMU_SCHED_HINT_W-1:0] trace_desc_sched_urgency_hint,
  input  logic                 trace_desc_kiloscore_extra_cvr_hint,
  input  logic                 trace_desc_sig_valid,
  input  logic [5:0]           trace_desc_query_sig,
  input  logic [5:0]           trace_desc_key_sig,
  input  logic [1:0]           trace_desc_prefix_class,
  input  logic [1:0]           trace_desc_router_class,
  input  logic                 trace_desc_wvalid,
  output logic                 trace_desc_wready,
  input  logic [DATA_W-1:0]    trace_desc_wdata,

  // Response output
  output logic                 resp_valid,
  input  logic                 resp_ready,
  output logic [DATA_W-1:0]    resp_rdata,
  output logic                 resp_hit,
  output logic                 resp_approx,

  // Backward-compatible simple memory interface
  output logic                 mem_re,
  output logic [ADDR_W-1:0]    mem_raddr,
  input  logic [DATA_W-1:0]    mem_rdata,
  input  logic                 mem_rvalid,
  output logic                 mem_we,
  output logic [ADDR_W-1:0]    mem_waddr,
  output logic [DATA_W-1:0]    mem_wdata,

  // Optional AXI-like memory interface (used when USE_AXI_IF=1)
  output logic [ADDR_W-1:0]    m_axi_araddr,
  output logic                 m_axi_arvalid,
  input  logic                 m_axi_arready,
  input  logic [DATA_W-1:0]    m_axi_rdata,
  input  logic                 m_axi_rvalid,
  output logic                 m_axi_rready,
  output logic [ADDR_W-1:0]    m_axi_awaddr,
  output logic                 m_axi_awvalid,
  input  logic                 m_axi_awready,
  output logic [DATA_W-1:0]    m_axi_wdata,
  output logic [(DATA_W/8)-1:0] m_axi_wstrb,
  output logic                 m_axi_wvalid,
  input  logic                 m_axi_wready,
  input  logic                 m_axi_bvalid,
  output logic                 m_axi_bready,

  output logic [31:0]          stat_demand_req_cnt,
  output logic [31:0]          stat_demand_miss_cnt,
  output logic [15:0]          stat_miss_rate_permille
);
  kcmu_top #(
    .ADDR_W(ADDR_W),
    .DATA_W(DATA_W),
    .LINES(LINES),
    .SCORE_W(SCORE_W),
    .TIME_W(TIME_W),
    .K_RECENT(K_RECENT),
    .H2O_V2_EN(H2O_V2_EN),
    .TRUE_H2O_RECENT_EN(TRUE_H2O_RECENT_EN),
    .TRUE_H2O_HH_EN(TRUE_H2O_HH_EN),
    .TRUE_H2O_BACKEND_ADMISSION_EN(TRUE_H2O_BACKEND_ADMISSION_EN),
    .UTILITY_HEAD_ADAPTIVE_EN(UTILITY_HEAD_ADAPTIVE_EN),
    .UTILITY_QUERY_AWARE_EN(UTILITY_QUERY_AWARE_EN),
    .UTILITY_COST_AWARE_EN(UTILITY_COST_AWARE_EN),
    .UTILITY_BACKEND_CRITICAL_EN(UTILITY_BACKEND_CRITICAL_EN),
    .UTILITY_SCORE_REPL_EN(UTILITY_SCORE_REPL_EN),
    .UTILITY_MARGINAL_REPL_EN(UTILITY_MARGINAL_REPL_EN),
    .MEM_RD_LATENCY(MEM_RD_LATENCY),
    .L2_RD_LATENCY(L2_RD_LATENCY),
    .L2_LINES(L2_LINES),
    .L2_WAYS(L2_WAYS),
    .L2_VB_LINES(L2_VB_LINES),
    .L2_VB_ENABLE(L2_VB_ENABLE),
    .L2_VB_CLEAN_READONLY_EN(L2_VB_CLEAN_READONLY_EN),
    .L2_WRITE_ALLOCATE(L2_WRITE_ALLOCATE),
    .L2_WRITE_THROUGH_EN(L2_WRITE_THROUGH_EN),
    .L2_BG_DIRTY_FLUSH_EN(L2_BG_DIRTY_FLUSH_EN),
    .L2_WRITE_ALLOC_QOS_TH(L2_WRITE_ALLOC_QOS_TH),
    .L2_READ_FILL_QOS_TH(L2_READ_FILL_QOS_TH),
    .L2_PREFETCH_FILL_QOS_TH(L2_PREFETCH_FILL_QOS_TH),
    .L2_SEM_FILL_RELAX_EN(L2_SEM_FILL_RELAX_EN),
    .L2_SEM_HOT_VICTIM_PROTECT_EN(L2_SEM_HOT_VICTIM_PROTECT_EN),
    .L2_SEM_HOT_SCORE_BONUS(L2_SEM_HOT_SCORE_BONUS),
    .L2_SEM_COLD_SCORE_PENALTY(L2_SEM_COLD_SCORE_PENALTY),
    .L2_SEM_HOT_MAX_AGE(L2_SEM_HOT_MAX_AGE),
    .L2_REQ_HOT_SCORE_BONUS(L2_REQ_HOT_SCORE_BONUS),
    .L2_AGE_STALE_SCORE_PENALTY(L2_AGE_STALE_SCORE_PENALTY),
    .L2_LOSSY_SCORE_PENALTY(L2_LOSSY_SCORE_PENALTY),
    .L2_LOSSY_COMPRESS_EN(L2_LOSSY_COMPRESS_EN),
    .L2_COMP_SHIFT(L2_COMP_SHIFT),
    .L2_COMPRESS_QOS_TH(L2_COMPRESS_QOS_TH),
    .L2_COMP_ERR_CAP(L2_COMP_ERR_CAP),
    .L1_BYPASS_QOS_TH(L1_BYPASS_QOS_TH),
    .L1_DEMAND_FILL_QOS_TH(L1_DEMAND_FILL_QOS_TH),
    .L1_PREFETCH_FILL_QOS_TH(L1_PREFETCH_FILL_QOS_TH),
    .L1_MISS_BYPASS_QOS_TH(L1_MISS_BYPASS_QOS_TH),
    .HIER_POLICY_EN(HIER_POLICY_EN),
    .L1_CONGEST_BYPASS_QOS_TH(L1_CONGEST_BYPASS_QOS_TH),
    .PREFETCH_CONGEST_QOS_TH(PREFETCH_CONGEST_QOS_TH),
    .PREFETCH_HBM_ISSUE_QOS_TH(PREFETCH_HBM_ISSUE_QOS_TH),
    .PREFETCH_HBM_ISSUE_RELAX_HOT(PREFETCH_HBM_ISSUE_RELAX_HOT),
    .EXEC_CONGEST_Q_LEVEL_TH(EXEC_CONGEST_Q_LEVEL_TH),
    .HBM_CONGEST_COLD_EXTRA_LAT(HBM_CONGEST_COLD_EXTRA_LAT),
    .HBM_CONGEST_HOT_EXTRA_LAT(HBM_CONGEST_HOT_EXTRA_LAT),
    .HBM_CONGEST_PREFETCH_EXTRA_LAT(HBM_CONGEST_PREFETCH_EXTRA_LAT),
    .L1_FILL_ON_HBM_MISS(L1_FILL_ON_HBM_MISS),
    .PF_ADAPT_EN(PF_ADAPT_EN),
    .PF_QOS_TH(PF_QOS_TH),
    .HBM_IF_Q_DEPTH(HBM_IF_Q_DEPTH),
    .HBM_IF_SERVICE_CYCLES(HBM_IF_SERVICE_CYCLES),
    .KV_MAP_ENABLE(KV_MAP_ENABLE),
    .KV_BLOCK_OFF_BITS(KV_BLOCK_OFF_BITS),
    .KV_DIR_ENTRIES(KV_DIR_ENTRIES),
    .KV_REAL_LAYOUT_EN(KV_REAL_LAYOUT_EN),
    .KV_TOKEN_BLOCK_BITS(KV_TOKEN_BLOCK_BITS),
    .KV_TYPE_ADDR_BIT(KV_TYPE_ADDR_BIT),
    .KV_MAP_SCORE_REPL_EN(KV_MAP_SCORE_REPL_EN),
    .KV_MAP_SCORE_REPL_HW_WIN(KV_MAP_SCORE_REPL_HW_WIN),
    .KV_MAP_SCORE_PROTECT_TH(KV_MAP_SCORE_PROTECT_TH),
    .KV_MAP_SCORE_DECAY_EN(KV_MAP_SCORE_DECAY_EN),
    .KV_MAP_SCORE_DECAY_LOG2(KV_MAP_SCORE_DECAY_LOG2),
    .ATTN_SCHED_EN(ATTN_SCHED_EN),
    .USE_AXI_IF(USE_AXI_IF)
  ) u_kcmu_top (
    .*
  );
endmodule

